[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  from = "/server/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/console/*"
  to = "/.netlify/functions/app/:splat"
  status = 200