[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  included_files = ["console/**"]

[[redirects]]
  from = "/pagini"
  to = "/pagini"
  status = 200
  
[[redirects]]
  from = "/server/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/console/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "./"
  status = 200