[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  included_files = ["console/**"]
  
[[redirects]]
  from = "/server/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/console/*"
  to = "/.netlify/functions/console/:splat"
  status = 200